### ISSUE TITLE
nis-suite failing

### ISSUE THREAD

**Issue by MalloZup** [okirch/twopence-nis#2]
Hi Olaf,

analyzing the nis-suite result, i found it out this failure:

```
client: rcypserv start
FAIL: client: command "rcypserv start" failed: status 127
```

https://github.com/okirch/twopence-nis/blob/master/twopence/nodes#L14

Reading the node file, i saw that the the server contain the ypserv package, where this command is packaged, but the client not.

I'm running the suite right now, on sles-11-sp4 to see if we have a new packaging issue.

**Comment by MalloZup** [comment]
this command is called on function :  

```
nis_init_slave_server(slave):
---
   journal.beginTest("starting ypserv")
        if not slave.runOrFail("rcypserv start"):
                return False
```

as slave we have the client node, that doesn't have the package installed.

**Comment by MalloZup** [comment]
OK regression was introduced on this commit : 

commit b8a0e42730d59b0cfd7458b57c8464c6fd4a30b6
Author: Thorsten Kukuk 
Date:   Fri Feb 26 13:08:58 2016 +0100

+
+##################################################################
+# Start slave ypserv and run some sanity checks
+##################################################################
+def nis_init_slave_server(slave):
-       global journal
  +

I think that Thorsten forgot to add this package on the node-file.

**Comment by okirch** [comment]
I think this came in as part of the NIS slave testing stuff. In the short term, it should help to edit the config file to install the ypserv package on the client, too.

Longer term, this test probably needs a third node on which we run the slave.

Olaf

**Comment by MalloZup** [comment]
thx Olaf! 
 i will fix the node file to avoid the failure.
In long term i agree with you that we create the additional node .

**Comment by MalloZup** [comment]
FIXED. suite-nis is now stable and ready to catch new failures :)!

**Comment by MalloZup** [comment]
i rebuild the package on obs :)
